name: Package code for Azure function

on:
  push:
    branches:
    # - master
    - update-workflow
    paths:
    - src/box-service/**
    - src/item-service/**
    - src/pos-service/**
    - src/stock-service/**
  workflow_dispatch:

env:
  dotnet-version: '3.1.x'

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        path: 
        - src/box-service
        - src/item-service
        - src/pos-service
        - src/stock-service

    defaults:
      run:
        shell: pwsh

    steps:
    - run: echo $CONTEXT | jq
      env:
        CONTEXT: ${{ toJson(github) }}
    - uses: actions/checkout@v2
    # - name: Check updates in ${{ matrix.path }}
    #   run: |

    - name: Setup .NET Core SDK ${{ env.dotnet-version }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.dotnet-version }}
    - uses: actions/cache@v2
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget
