name: Package code for Azure function

on:
  push:
    branches:
    # - master
    - update-workflow
    paths:
    - src/box-service/**
    - src/item-service/**
    - src/pos-service/**
    - src/stock-service/**
  workflow_dispatch:

env:
  dotnet-version: '3.1.x'
  artifact-name-function-package: function-packages

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        service:
        - target_paths:
          - src/box-service/
          build_path: src/box-service/BoxManagementService
          package_file_name: BoxManagementService.zip
        - target_paths:
          - src/item-service/
          build_path: src/item-service/ItemService.ItemMaster
          package_file_name: ItemService.ItemMaster.zip
        - target_paths:
          - src/pos-service/
          build_path: src/pos-service/PosService
          package_file_name: PosService.zip
        - target_paths:
          - src/stock-service/StockService.StockCommand/
          - src/stock-service/StockService.Core/
          build_path: src/stock-service/StockService.StockCommand
          package_file_name: StockService.StockCommand.zip
        - target_paths:
          - src/stock-service/StockService.StockProcessor/
          - src/stock-service/StockService.Core/
          build_path: src/stock-service/StockService.StockProcessor
          package_file_name: StockService.StockProcessor.zip
        - target_paths:
          - src/stock-service/StockService.StockQuery/
          - src/stock-service/StockService.Core/
          build_path: src/stock-service/StockService.StockQuery
          package_file_name: StockService.StockQuery.zip

    env:
      output-dir: ${{ github.workspace }}/outputs
      
    steps:
    # - name: Get diff
    #   id: get_diff
    #   uses: octokit/request-action@v2.x
    #   with:
    #     route: GET /repos/:repo/compare/:base...:head
    #     repo: ${{ github.repository }}
    #     base: ${{ github.event.before }}
    #     head: ${{ github.event.after }}
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    # - name: Check updates under ${{ matrix.target_path }}
    #   id: check_updates
    #   shell: bash
    #   run: |
    #     COUNT=`echo $FILES | jq "map(select(. | startswith(\"${TARGET_PATH}\"))) | length"`
    #     echo "::set-output name=COUNT::${COUNT}"
    #   env:
    #     FILES: ${{ toJson(fromJson(steps.get_diff.outputs.data).files.*.filename) }}
    #     TARGET_PATH: ${{ matrix.target_path }}
    # - uses: actions/checkout@v2
    #   if: ${{ fromJson(steps.check_updates.outputs.COUNT) > 0 }}

    - name: Count commits
      id: count_commits
      shell: bash
      run: |
        COUNT=`echo ${COMMITS} | jq 'length'`
        echo "::set-output name=COUNT::${COUNT}"
      env:
        COMMITS: ${{ toJson(github.event.commits.*.id) }}
    - uses: actions/checkout@v2
      with:
        fetch-depth: ${{ steps.count_commits.outputs.COUNT + 1 }}
    - name: Check updates under target paths
      id: check_updates
      shell: bash
      run: |
        COUNT=`git diff --name-only ${BEFORE} ${AFTER} ${TARGET_PATHS} | wc -l`
        echo "::set-output name=COUNT::${COUNT}"
      env:
        BEFORE: ${{ github.event.before }}
        AFTER: ${{ github.event.after }}
        TARGET_PATHS: ${{ join(matrix.service.target_paths, ' ') }}
    - name: Setup .NET Core SDK ${{ env.dotnet-version }}
      if: ${{ steps.check_updates.outputs.COUNT > 0 }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.dotnet-version }}
    - uses: actions/cache@v2
      if: ${{ steps.check_updates.outputs.COUNT > 0 }}
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget
    - name: Build package
      run: |
        pushd ${{ matrix.service.build_path }}
        dotnet restore
        dotnet build --configuration Release
        dotnet publish --configuration Release --output ${{ env.output-dir }}
        popd
    - name: Archive
      run: |
        Compress-Archive -Path ${{ env.output-dir }}/* -DestinationPath ${{ matrix.service.package_file_name }}
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ env.artifact-name-function-package }} ${{ matrix.service.package_file_name }}
        path: ${{ matrix.service.package_file_name }}

  deploy:
    runs-on: ubuntu-latest
    needs:
    - build

    steps:
    - uses: actions/download-artifact@v2
    - run: ls -la
